# Exploritory Data Analysis (EDA)

This dataset is from Kaggle: DoorDash ETA Prediction and it contains historical delivery records from DoorDash in early 2015 for a subset of cities.

- Each row represents one delivery

- Data includes order details, timing, market identifiers, and operational metrics

- All monetary values are in cents

- All time durations are in seconds

- Some values have been noised to protect business-sensitive information

# Import Libraries and Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/historical_data.csv")

# Inital Data Exploration

In [3]:
df.head()

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration
0,1.0,2015-02-06 22:24:17,2015-02-06 23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0
1,2.0,2015-02-10 21:49:25,2015-02-10 22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0
2,3.0,2015-01-22 20:39:28,2015-01-22 21:09:09,5477,NaN,1.0,1,1900,1,1900,1900,1.0,0.0,0.0,446,690.0
3,3.0,2015-02-03 21:21:45,2015-02-03 22:13:00,5477,NaN,1.0,6,6900,5,600,1800,1.0,1.0,2.0,446,289.0
4,3.0,2015-02-15 02:40:36,2015-02-15 03:20:26,5477,NaN,1.0,3,3900,3,1100,1600,6.0,6.0,9.0,446,650.0

In [4]:
df.shape

(197428, 16)

In [5]:
df.describe()

,market_id,store_id,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration
count,196441.000000,197428.000000,196433.000000,197428.000000,197428.000000,197428.000000,197428.000000,197428.000000,181166.000000,181166.000000,181166.000000,197428.000000,196902.000000
mean,2.978706,3530.510272,2.882352,3.196391,2682.331402,2.670791,686.218470,1159.588630,44.808093,41.739747,58.050065,308.560179,545.358935
std,1.524867,2053.496711,1.503771,2.666546,1823.093688,1.630255,522.038648,558.411377,34.526783,32.145733,52.661830,90.139653,219.352902
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,-86.000000,0.000000,-4.000000,-5.000000,-6.000000,0.000000,0.000000
25%,2.000000,1686.000000,1.000000,2.000000,1400.000000,1.000000,299.000000,800.000000,17.000000,15.000000,17.000000,251.000000,382.000000
50%,3.000000,3592.000000,3.000000,3.000000,2200.000000,2.000000,595.000000,1095.000000,37.000000,34.000000,41.000000,251.000000,544.000000
75%,4.000000,5299.000000,4.000000,4.000000,3395.000000,3.000000,949.000000,1395.000000,65.000000,62.000000,85.000000,446.000000,702.000000
max,6.000000,6987.000000,7.000000,411.000000,27100.000000,20.000000,14700.000000,14700.000000,171.000000,154.000000,285.000000,2715.000000,2088.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197428 entries, 0 to 197427
Data columns (total 16 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   market_id                                     196441 non-null  float64
 1   created_at                                    197428 non-null  object
 2   actual_delivery_time                          197421 non-null  object
 3   store_id                                      197428 non-null  int64
 4   store_primary_category                        192668 non-null  object
 5   order_protocol                                196433 non-null  float64
 6   total_items                                   197428 non-null  int64
 7   subtotal                                      197428 non-null  int64
 8   num_distinct_items                            197428 non-null  int64
 9   min_item_price                                197428 non-null  int64
 10  max_item_price                                197428 non-null  int64
 11  total_onshift_dashers                         181166 non-null  float64
 12  total_busy_dashers                            181166 non-null  float64
 13  total_outstanding_orders                      181166 non-null  float64
 14  estimated_order_place_duration                197428 non-null  int64
 15  estimated_store_to_consumer_driving_duration  196902 non-null  float64
dtypes: float64(6), int64(7), object(3)
memory usage: 24.1+ MB

## Changing Data Types

In [7]:
df['created_at'] = pd.to_datetime(df['created_at'])
df['actual_delivery_time'] = pd.to_datetime(df['actual_delivery_time'])

# Data Cleaning Summary

In [8]:
df.isnull().sum()

market_id                                         987
created_at                                          0
actual_delivery_time                                7
store_id                                            0
store_primary_category                           4760
order_protocol                                    995
total_items                                         0
subtotal                                            0
num_distinct_items                                  0
min_item_price                                      0
max_item_price                                      0
total_onshift_dashers                           16262
total_busy_dashers                              16262
total_outstanding_orders                        16262
estimated_order_place_duration                      0
estimated_store_to_consumer_driving_duration      526
dtype: int64

Finding the % of data missing in each column

In [9]:
df.isnull().sum()/df.shape[0]*100

market_id                                       0.499929
created_at                                      0.000000
actual_delivery_time                            0.003546
store_id                                        0.000000
store_primary_category                          2.411006
order_protocol                                  0.503981
total_items                                     0.000000
subtotal                                        0.000000
num_distinct_items                              0.000000
min_item_price                                  0.000000
max_item_price                                  0.000000
total_onshift_dashers                           8.236927
total_busy_dashers                              8.236927
total_outstanding_orders                        8.236927
estimated_order_place_duration                  0.000000
estimated_store_to_consumer_driving_duration    0.266426
dtype: float64

In [10]:
df[df[["total_onshift_dashers", "total_busy_dashers", "total_outstanding_orders"]].isnull()]

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration
0,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197423,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197424,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197425,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197426,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197427,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

These three are missing from the same rows so it's better to just drop those rows and we would just lose ~8.3% of the rows.

In [11]:
df.dropna(subset = ["total_onshift_dashers", "total_busy_dashers", "total_outstanding_orders","actual_delivery_time"], inplace=True)

Market_id means the region is missing which is likely that those can be failed deliveries, so it is best to drop those rows

In [12]:
df.dropna(subset=['market_id'],inplace=True)

In [13]:
df.shape

(180240, 16)

Filling store_primary_category with Unkown and order_protocal with -1.

In [14]:
df.store_primary_category.fillna("unknown",inplace=True)
df.order_protocol.fillna(-1, inplace= True)

/tmp/ipykernel_2186/3531564852.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.store_primary_category.fillna("unknown",inplace=True)
/tmp/ipykernel_2186/3531564852.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.order_protocol.fillna(-1, inplace= True)

Filling null estimated_store_to_consumer_driving_duration with the median of each market

In [15]:
#df.dropna(subset=["estimated_store_to_consumer_driving_duration"],inplace=True)
df['estimated_store_to_consumer_driving_duration'] = (
    df.groupby('market_id')['estimated_store_to_consumer_driving_duration']
      .transform(lambda x: x.fillna(x.median()))
)

In [16]:
df.shape

(180240, 16)

# Extracting Features

### delivery_duration

- The time between when the order was created and the time it was delivered in minutes.

In [17]:
df['delivery_duration'] = (df['actual_delivery_time'] - df['created_at']).dt.total_seconds()/60

### estimated_delivery_duration

- The total estimated duration which includes the time it takes to prepare the food and the time it takes to deilver it.

In [18]:
df["estimated_delivery_duration"] = (
    df["estimated_order_place_duration"] + df["estimated_store_to_consumer_driving_duration"]
)/60

### delay

- The delay it took that is the difference between the estimated delivery duration and the actual delivery duration.

In [19]:
df['delay'] = df['delivery_duration'] - df['estimated_delivery_duration']

### hour_of_day

- The hour of the day when the order was placed.

In [20]:
df['hour_of_day'] = df['created_at'].dt.hour

# Exporting the clean dataframe

In [21]:
df.to_csv("clean_dataset.csv", index=False)